# Generated by Django 4.1.3 on 2022-12-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=9)),
                ('combustible', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Persona',
            new_name='Cliente',
        ),
    ]
