# Generated by Django 4.1.3 on 2022-12-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_coche_rename_persona_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Persona',
        ),
        migrations.DeleteModel(
            name='Coche',
        ),
    ]
